### ISSUE TITLE
Heads up: Fossies.org offers optional source code misspelling check using <wait for it> codespell

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#1315]
> Although misspelling corrections are not the most exciting issues and the spelling errors are rarely true code bugs but mostly contained in the comment and documentation parts they corrections can still improve the overall quality of a software project a bit.

> So since October 2019 Fossies offers optionally source code misspelling check reports using as basis the command line tool "codespell". The resulting analysis reports are currently per default not linked, on the one hand since they are essentially only of interest to the authors itself, on the other hand to avoid a taste of know-all-manner and snooping around. But if available they will be visible by directly accessing URLs like
```
  https://fossies.org/<folder>/<package>/codespell.html
```

source: https://fossies.org/features.html#codespell

**Comment by jschleus** [comment]
Yes, and here is the according report for the "codespell" project itself:

https://fossies.org/linux/misc/codespell-1.16.0.tar.gz/codespell.html

 or version independent

 https://fossies.org/linux/misc/codespell/codespell.html

Congratulations!

A little more exciting this test report for the project "pcre":

https://fossies.org/linux/misc/pcre/codespell.html

Since til now no according reports were requested I did some unrequested ones for a few selected FOSS projects and informed the project author(s) resp. maintainer(s). Til now the feedback was - a little bit surprising for me - mostly positive.

Thanks for "codespell"!

**Comment by larsoner** [comment]
Thanks for the info, seems like no action needed so I'll close
