### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by candrews** [codespell-project/codespell#1698]
There have been many commits and much work done since the last release, v1.17.1 on May 22 - 5 month ago.

Can you please make a new release so we can all benefit from the great work done over the past 5 months?

**Comment by peternewman** [comment]
I think it would be good to get #1669 in at least and I think there are a few others, but yes I'd agree in principal.

I think there were a few other little bits to get in, but they could perhaps wait.

**Comment by larsoner** [comment]
@peternewman let me know when you're happy and I can cut a new release

**Comment by rkm** [comment]
Hi folks. Just wondering if there has been any progress on this since last month? I'm very appreciative of the work that's been done here, and would love to use some of the new features like the `--config` support!

Fwiw I was a bit confused after seeing this in the README but found it not to be available in the latest release. I'm not familiar with your release process, but perhaps it would be less confusing to new users if unreleased changes were not published to the README until they are available?

**Comment by sebweb3r** [comment]
Hey,

the Readme is up to date with the master branch. If you install the version of the master branch [1], you get the feature. The only option would be to have a develop branch and 
only push releases to master. But this would confuse other people.

[1] pip3 install git+https://github.com/codespell-project/codespell.git

**Comment by peternewman** [comment]
> @peternewman let me know when you're happy and I can cut a new release

Sorry all, I thought I'd made a milestone before, but I think I'd only thought about it. Then life took over.

**Comment by peternewman** [comment]
I did milestone, but in https://github.com/codespell-project/actions-codespell !
