### ISSUE TITLE
Time for new release?

### ISSUE THREAD

**Issue by bwitt** [codespell-project/codespell#1923]
There have been a ton of fixes and dictionary changes since the last release; it'd be great to have a new release to take advantage of them.

**Comment by peternewman** [comment]
Personally I wouldn't say there have been a vast amount of fixes since the last release, although lots of dictionary changes:
https://github.com/codespell-project/codespell/compare/v2.0.0...master

I've tagged some (non-dictionary) PRs, I'd suggest it might be nice to get in before a release:
https://github.com/codespell-project/codespell/milestone/1

FWIW, for me at least I run the git version in my CI to pick up the latest typos (and to avoid big bang hits of new additions which need fixing).

**Comment by larsoner** [comment]
@peternewman I'm inclined to cut a release. We can always do another one quickly after those other PRs are merged

**Comment by peternewman** [comment]
Fair enough, sounds reasonable. Would you mind looking at, and hopefully merging, my #1858 though first @larsoner (although obviously feel free to just cut the release if my PR needs more work in your opinion).

**Comment by sylvestre** [comment]
@larsoner
Hello
Can we have a new release ? :)
Thanks!
