### ISSUE TITLE
Proposal: switch to pre-commit framework for running linters and pre-commit.ci for checking in CI

### ISSUE THREAD

**Issue by bwitt** [codespell-project/codespell#2076]
I notice this project is using github actions to run flake8; if we switched to https://pre-commit.com/ to configure and run linters (like flake8) and https://pre-commit.ci/ to run this in CI, it would have some benefits:

can optionally check linters locally via pre-commit before pushing, using the same versions of the linters (using the same config file)
can add a bunch of other linters via the same framework, just add to the one config file
pre-commit ci can auto fix some errors and update the PR with the changes automatically
pre-commit ci supports automatic generation of PRs to update versions of linters, so you'd get a PR updating versions automatically.

However, I'm not sure that the errors from a pre-commit ci run will appear on the PR itself like the current github action flake8 does.  
I'm not too familiar with the benefits of the github action; maybe there are other differences too?

What do you think?

**Comment by peternewman** [comment]
> can optionally check linters locally via pre-commit before pushing, using the same versions of the linters (using the same config file)

We already have our flake8 config in a file in the repo, so the same linter version bit is the only relevant part of this.

> pre-commit ci can auto fix some errors and update the PR with the changes automatically

This seems worrying to me, rather than a benefit. Consider the odd reports people have of bugs they've found, we wouldn't want it silently fixing spelling errors.

Something like this seems a safer/better solution to that problem, although has some current issues due to GitHub limitations:
https://github.com/getsentry/action-git-diff-suggestions

> pre-commit ci supports automatic generation of PRs to update versions of linters, so you'd get a PR updating versions automatically.

I guess that could be nice, but as per #2073 stuff may break when the linter is updated, I guess this just contains it in one PR.

> However, I'm not sure that the errors from a pre-commit ci run will appear on the PR itself like the current github action flake8 does.

I suspect they won't, which for me is one of the big benefits of GitHub actions and why I've migrated stuff here and elsewhere from Travis to Actions. To me that seems a lot more user-friendly than expecting someone to read loads of CI logs looking for an issue.

Perhaps you could test the suggestion stuff with a test repo/fork or see someone else who's already using it?

> I'm not too familiar with the benefits of the github action; maybe there are other differences too?

I assume they should be a bit more tightly coupled than external stuff and probably a bit less likely to mess us around like Travis which I was personally bitten by.

> What do you think?

We've got our pre-commit hook:
https://github.com/codespell-project/codespell/blob/master/.pre-commit-hooks.yaml

I assume this wouldn't clash with that? There's probably no harm in adding pre-commit config for local users (which will basically just say run flake8, even if we don't use it for CI.

IIRC there's also a pre-commit action for GitHub actions and you can link problem matchers into it too, which might get the best of both worlds?

**Comment by bwitt** [comment]
>> pre-commit ci can auto fix some errors and update the PR with the changes automatically
> This seems worrying to me, rather than a benefit. Consider the odd reports people have of bugs they've found, we wouldn't want it silently fixing spelling errors.

I mean if the pre-commit linters such as flake8 find a problem they can automatically fix on the PR, it can create a new commit on the PR, fixing those. The changes would be in the PR, so you'd still see them.  It wouldn't be running codespell on itself, since that's like a unit test and would still be in the existing github actions.  That's a downside also if we're not switching everything over to pre-commit (which I don't think we should); we'd still have github actions running some things, and pre-commit.ci running others. Did I understand what your point?  I'm not sure I understand what you mean here.

> I assume this wouldn't clash with [the pre-commit hook]? There's probably no harm in adding pre-commit config for local users (which will basically just say run flake8, even if we don't use it for CI.

Correct, this would be separate from the pre-commit hook.  And yes we could add a pre-commit config which people could optionally run locally. 

> IIRC there's also a pre-commit action for GitHub actions and you can link problem matchers into it too, which might get the best of both worlds?

Yes I saw that!  But it's been deprecated and the author is recommending using pre-commit.ci so that's why I was going in the pre-commit.ci direction.
https://github.com/marketplace/actions/pre-commit

> Perhaps you could test the suggestion stuff with a test repo/fork or see someone else who's already using it?

Good idea let me see what I can do/find.

**Comment by bwitt** [comment]
Yes looking good!  Thanks!
