### ISSUE TITLE
Comments to skip specific instances or lines

### ISSUE THREAD

**Issue by plaindocs** [codespell-project/codespell#2096]
Hey Folks,

Super good work on this, I've just implemented it over in [WTD](https://github.com/writethedocs/www/pull/1608). Thanks!

A lot the exceptions I've added to my exception file are single use exceptions, I'd like them to be treated as mistakes in most cases, just not in the particular ones that are flagged.

Some linters have a comment toggle system where you can do something like

```
This text is linted

<!-- codespell: off -->

This text is not linted

<!-- codespell: on -->

This text is linted
```

I guess as codespell isn't language aware, implementing something like that is trickier? Would be a useful addition though.

**Comment by matkoniecz** [comment]
See #1601 "Does codespell support skipping the presence of a word in a specific file, but still search for it elsewhere?"

For me encouraging such scarring of code is a really, really bad idea. In my opinion such exceptions really should be in linter config rather than littering code.

**Comment by plaindocs** [comment]
Thanks for the explanation.

**Comment by peternewman** [comment]
> For me encouraging such scarring of code is a really, really bad idea. In my opinion such exceptions really should be in linter config rather than littering code.

It makes sense for code when you want to ignore a particular line, but doesn't work so well in documentation. Otherwise you hit these same issues of needing to have another document where you track what you're ignoring (which loses the context).

The problem with a general tool like this, rather than say a Python linter, is that the suitable escape format varies completely by language and would be quite a pain to manage, and as I say doesn't work for say a plain text file.

**Comment by plaindocs** [comment]
Yeah, it does make sense.

The majority of the problematic ones for me are the 2 and 3 character ones I think, so a different option would be to exclude those.

But I'm super happy with it as is! 

And thanks for the pointer to the GitHub action @peternewman
