### ISSUE TITLE
Remove commend -> comment, command

### ISSUE THREAD

**Issue by janosh** [codespell-project/codespell#2319]
Commend is a widely used word:

> To compliment or praise someone for something that they have done. I have to commend you for your extraordinary bravery in a dangerous situation.

Not sure if the thinking here was that it would be more often a typo than used intentionally? Certainly not the case for me. I've encountered this rule as a false-positive several times now.

**Comment by peternewman** [comment]
Hi @janosh ,

Unfortunately the first page of grep.app disproves this:
https://grep.app/search?q=commend&words=true

It's in rare exactly because you say, the typo is probably more likely (in a code context) than the genuine word.

You can either drop that entire dictionary, or skip that one "typo". Because its got two corrections it will never auto-fix to the suggestion, so it's pretty low risk.

**Comment by janosh** [comment]
Cool, didn't know about grep.app. Well, I'll withdraw my claim then. 😄

**Comment by peternewman** [comment]
Yeah we use it quite a bit, it seems to be a bit better than just the GitHub code search.

I've pondered in the past, and I'm sure we'll do it eventually, to split the rare dictionary into two, either into stuff that doesn't appear in any electronic source dictionary, or possibly just the core aspell dictionary versus outside the core, at which point things like commend may move into one that gets disabled by default or something.

See also #2281 amongst others.
