### ISSUE TITLE
`astroid` in `requirements.txt`

### ISSUE THREAD

**Issue by jamesbraza** [codespell-project/codespell#2867]
[`astroid`](https://github.com/pylint-dev/astroid) is a dependency of [`pylint`](https://github.com/pylint-dev/pylint), a major python linter.

`codespell==v2.2.4` is marking `astroid` as a typo in my `requirements.txt` file (autogenerated from `requirements.in` by [`pip-tools`](https://github.com/jazzband/pip-tools)'s `pip-compile` command):

```txt
requirements.txt:15: astroid ==> asteroid
requirements.txt:86: astroid ==> asteroid
requirements.txt:300: astroid ==> asteroid
```

This is halfway a question, halfway an issue.

1. Should package names in `requirements.txt`/`.in` be checked?
2. Should typo package names be considered misspellings by `codespell`?

**Comment by DimitriPapadopoulos** [comment]
And a third question from myself:

3. Chances are there are other false positives in any large project, which means you will have to maintain a list of words to ignore any way. Why not add `astroid` to the list of words to ignore?
   What I am trying to say, is that codespell will always report false positives and skip false negatives. A tool based on dictionaries cannot be perfect – tools based on deep learning might do better.

And my _personal_ view, maintainers are free to jump in with a different one:

1. Only you know the answer: it is up to the project to decide how to use tools. From my experience, the chances of a misspelling in a file like `requirements.txt` are dim, because it contains only package names and no “free text”. I would expect misspellings to be caught any way at build time. On the other hand, a **real** typo (a true positive) in such a file would certainly qualify as a bug, not a simple typo.
2. Note that codespell depends on multiple dictionaries, so it depends on the dictionaries you use – including your own dictionaries in some cases. About the main dictionary: Yes, names that contain intentional misspellings, such as place or person names or trademarks, may appear in it. This is inevitable, see for example #2811. Which dictionaries such misspellings appear in, if any, depends on many factors, already discussed here: https://github.com/codespell-project/codespell/pull/2865#issuecomment-1571786423, https://github.com/codespell-project/codespell/pull/2865#issuecomment-1571830417. I fell that matnainers of astronomy software will be unhappy if we do not catch `astroid`.

By the way, #2865 could have been re-opened, giving maintainers* an opportunity to jump in over there. I haven't written that #2865 will not be merged – I just do not feel like merging it on my own.

\* Funnily I do not have a list of the accounts with _Maintain_ or _Admin_ roles in codespell, as GitHub does not seem to give away that list, even to those with _Write_ roles

**Comment by jamesbraza** [comment]
Yeah I do agree that `astroid` is an incorrect spelling, I can see both arguments made in #2865.

I think `codespell` should be able to ignore entire files, and in my use case `^requirements\S*\.(in|txt)$` is one of them.

Does `codespell` support the ability to ignore entire files (ideally by regex or a list)?  I see `--exclude-file`, but that seems to be more a blocklist of words, not a blocklist of file names.

**Comment by DimitriPapadopoulos** [comment]
The _codespell_ option names felt unnatural when I started using the tools. I couldn't find the reason, and was therefore unable to suggest a change. Now that I think of it, one reason might be that _grep_ options `--exclude-dir` and `--exclude` skip directories and files.

The _codespell_ option you're after is **`--skip`**.

**Comment by jamesbraza** [comment]
Alright thank you!  I understand and have my resolution, which is to use:

```shell
codespell --skip=requirements.in,requirements.txt
```

If using `pre-commit`, this can alternately be attained (around `codespell`) with the `exclude` option.

---

A possible resolution for `codespell`, is to have its own default skip list of files, and add `requirements\S*\.(in|txt)` to it.  While at it, there's probably many file/folder names to add to this (e.g. `venv`/`.venv`).  However, as @DimitriPapadopoulos describes above, this type of endeavor comes with tradeoffs and assumptions.

I will close this out, feel free to re-open anyone in perpetuity!

**Comment by DimitriPapadopoulos** [comment]
Currently, _codespell_ is file name or rather file type-agnostic.

Support or plugins for different file types make sense, including for skipping files not worth spellchecking. However, that requires more involvement than I at least am capable of. There are other tickets requesting that.
