### ISSUE TITLE
Feature: CI test for missing '->' in dictionary.txt

### ISSUE THREAD

**Issue by luzpaz** [codespell-project/codespell#304]
Similar to #303 but incorporate a CI regex test on `dictionary.txt` for any missing `->` strings. The regex: `^(.(?!(->)))*$` to use.

**Comment by larsoner** [comment]
Feel free to open PRs. I'd suggest making a commit to add the functionality, a commit that shows that it works (by adding an errant entry and showing that the regex catches it), then a commit to undo the error. Then when merging we'll merge by squash+rebase so that only the CI changes persist in history.

**Comment by flopp** [comment]
That's already indirectly done by https://github.com/codespell-project/codespell/blob/39869940197b61b9fdf6e02ac02cf567e258040a/codespell_lib/tests/test_dictionary.py#L15

```
line = "line->with,arrow,"
err, rep = line.split('->')
# works without exception
```
```
line = "line without arrow"
err, rep = line.split('->')
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ValueError: not enough values to unpack (expected 2, got 1)
```

```
line = "line->with->multiple->arrows"
err, rep = line.split('->')
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ValueError: too many values to unpack (expected 2)
```
