### ISSUE TITLE
Does `.codespellrc` support comments?

### ISSUE THREAD

**Issue by your-diary** [codespell-project/codespell#3229]
[*Using a config file*](https://github.com/codespell-project/codespell#using-a-config-file) in `README.md` says nothing about it.

It seems `#` and `//` both work, but are these officially supported as comments or a bug?

**Comment by DimitriPapadopoulos** [comment]
It's an INI file. We read it using [configparser.ConfigParser](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure) so the format is pretty standard and beyond our direct reach. Both `#` and `;` work according to the previous link. I am surprised `//` works, because it's really not standard.

We should probably specify the config files are [INI files](https://en.wikipedia.org/wiki/INI_file).

**Comment by your-diary** [comment]
Thank you.

I just confirmed `configparser.ConfigParser()` is used in [`codespell_lib/_codespell.py`](https://github.com/codespell-project/codespell/blob/master/codespell_lib/_codespell.py#L554).

> I am surprised // works, because it's really not standard for INI files.

I noticed any symbols work:
```
[codespell]

#These are all ignored.
* ignore-words-list = ect
+ ignore-words-list = ect
# ignore-words-list = ect
// ignore-words-list = ect
; ignore-words-list = ect
_ ignore-words-list = ect

#Only this works.
ignore-words-list = ect
```

Though it seems the comment characters can be customized via `comment_prefixes` parameter of `configparser.ConfigParser()` according to [*Customizing Parser Behaviour*](https://docs.python.org/3/library/configparser.html#customizing-parser-behaviour), the setting is not used in project.

> We should probably specify the config files are [INI files](https://en.wikipedia.org/wiki/INI_file).

I do agree with you.
