### ISSUE TITLE
assertIn false positivies

### ISSUE THREAD

**Issue by nijel** [codespell-project/codespell#3430]
Codespell 2.3.0 started to complain about [assertIn](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertIn) method:

```
weblate/lang/tests.py:330: assertIn ==> asserting, assert in, assertion
weblate/lang/tests.py:331: assertIn ==> asserting, assert in, assertion
```

I know I can allow this particular word, but complaining on standard Python test suite API seems a bit annoying.

**Comment by DimitriPapadopoulos** [comment]
How about moving it to the _code_ dictionary? Merge requests welcome.

**Comment by CodyCBakerPhD** [comment]
@DimitriPapadopoulos 

> How about moving it to the code dictionary? Merge requests welcome.

Happy to try to fix this, tracked it down to this entry in the global dict: https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt#L5633

What I'm not clear on is how moving this to `dictionary_code` would help; it seems what we would want it to do is ignore the specific capitalization of `.assertIn` (either pre-ambled by `self` or `TestCase`) when in `.py` files

Is there a separate place in codespell to specify conditional code-related ignores of items from the dictionary that would otherwise make sense in normal text?

**Comment by DimitriPapadopoulos** [comment]
There's the _code_ dictionary. Because codespell is language agnostic, you cannot define a rule for Python files only.

**Comment by peternewman** [comment]
> How about moving it to the _code_ dictionary? Merge requests welcome.

I've opened #3469 for this specific aspect.

> The code dictionary seems to have definitions of common misspellings of code, e.g.,

> ```
> agrv->argv
> ```

This shouldn't be in there as it will likely rarely be triggered, if you're checking code you won't use this dictionary (but it might not pass CI in the normal one where it would work because argv isn't a word in a proper dictionary.

> ```
> arange->arrange, a range,
> ```

This is a numpy function, so wants skipping if you're checking code (so it doesn't become arrange or a range):
https://numpy.org/doc/stable/reference/generated/numpy.arange.html

**Comment by DimitriPapadopoulos** [comment]
Can be closed after moving `assertin` to _code_.

For `agrv->argv` and similar entries, moved from _code_ to main dictionary in  #3470.
