### ISSUE TITLE
false positive: unparseable

### ISSUE THREAD

**Issue by polluks** [codespell-project/codespell#3444]
https://github.com/codespell-project/codespell/blob/3760e619e2a7b7fa8467debb2889d21a34651853/codespell_lib/data/dictionary.txt#L58550
Wiktionary says since 2008 https://en.wiktionary.org/wiki/unparseable

**Comment by DimitriPapadopoulos** [comment]
Yes, the difficulty is that I cannot find that word in most mainstream curated dictionaries, either as _parsable_ or as _parseable_:
* [Cambridge](https://dictionary.cambridge.org/fr/spellcheck/anglais/?q=unparsable)
* [Collins](https://www.collinsdictionary.com/spellcheck/english?q=unparsable)
* [Longman](https://www.ldoceonline.com/spellcheck/english/?q=unparsable)
* [Merriam-Webster](https://www.merriam-webster.com/dictionary/unparsable)
* [Oxford Learner's](https://www.oxfordlearnersdictionaries.com/spellcheck/english/?q=unparsable)

However, OED does have it, as _parsable_ only:
* [OED](https://www.oed.com/search/dictionary/?scope=Entries&q=unparsable)

I usually suggest we follow [SCOWL (And Friends)](http://wordlist.aspell.net/), as the mainstream source of correct spelling, but unfortunately it lacks both _parsable_ and `parseable`:
http://app.aspell.net/lookup?dict=en_US-large;words=unparsable
http://app.aspell.net/lookup?dict=en_US-large;words=unparseable

The commercial spellchecker I have tried does suggest to replace _parseable_ with _parseable_.

Searching [_parsable vs parseable_](https://www.google.com/search?q=parsable+vs+parseable) comes up with pages mostly (but not always) suggesting to use _parsable_ instead of _parseable_, for example:
* https://word.tips/spelling/parsable-vs-parseable/
* https://whichiscorrect.com/parsable-vs-parseable/#google_vignette

Grammar books suggest that the final ***e*** of the root word is dropped, except if the root word ends in ***ce*** or ***ge***. That usually remains a suggestion, but I feel _parsable_ should be preferred in formal usage.

The Google Ngram Viewer shows  _parsable_ remains more common than _parseable_, but the difference is not significant enough to rule out _parseable_:
https://books.google.com/ngrams/graph?content=unparsable%2Cunparseable&year_start=1800

In any case, if we are to remove this entry, we should review other occurrences of ***-eable*** for consistency:
```console
$ grep 'eable->' codespell_lib/data/dictionary.txt | wc -l
87
$ 
```

**Comment by DimitriPapadopoulos** [comment]
By the way, this entry suggests that _writeable_ is the British spelling while _writable_ is American spelling:
```console
$ grep 'eable->' codespell_lib/data/dictionary_en-GB_to_en-US.txt 
writeable->writable
$ 
```
Total nonsense:
https://books.google.com/ngrams/graph?content=writable%2Cwriteable&year_start=1900&year_end=2019&corpus=en-GB-2019
https://books.google.com/ngrams/graph?content=writable%2Cwriteable&year_start=1800&year_end=2019&corpus=en-US-2019

**Comment by DimitriPapadopoulos** [comment]
Time permitting, I would like to review and search in [SCOWL](http://app.aspell.net/lookup?dict=en_US-large) the 89 _-eable_ entries found in codespell dictionaries. If SCOWL usually accepts both variannts, I am happy to discard all such entries. Help welcome!

<details>
<summary>-eable entries in codespell dictionaries</summary>

```console
$ grep 'eable->' codespell_lib/data/dictionary*.txt
codespell_lib/data/dictionary_code.txt:cloneable->clonable
codespell_lib/data/dictionary.txt:acchieveable->achievable
codespell_lib/data/dictionary.txt:achiveable->achievable
codespell_lib/data/dictionary.txt:adviseable->advisable
codespell_lib/data/dictionary.txt:aggreeable->agreeable
codespell_lib/data/dictionary.txt:agreable->agreeable
codespell_lib/data/dictionary.txt:agreeeable->agreeable
codespell_lib/data/dictionary.txt:arrangteable->arrangeable
codespell_lib/data/dictionary.txt:availeable->available
codespell_lib/data/dictionary.txt:beable->be able
codespell_lib/data/dictionary.txt:beliveable->believable
codespell_lib/data/dictionary.txt:browseable->browsable
codespell_lib/data/dictionary.txt:centrifugeable->centrifugable
codespell_lib/data/dictionary.txt:compareable->comparable
codespell_lib/data/dictionary.txt:compileable->compilable
codespell_lib/data/dictionary.txt:configureable->configurable
codespell_lib/data/dictionary.txt:createable->creatable
codespell_lib/data/dictionary.txt:customizeable->customizable
codespell_lib/data/dictionary.txt:debateable->debatable
codespell_lib/data/dictionary.txt:decideable->decidable
codespell_lib/data/dictionary.txt:defineable->definable
codespell_lib/data/dictionary.txt:deleteable->deletable
codespell_lib/data/dictionary.txt:derageable->dirigible
codespell_lib/data/dictionary.txt:desireable->desirable
codespell_lib/data/dictionary.txt:deviceremoveable->deviceremovable
codespell_lib/data/dictionary.txt:eforceable->enforceable
codespell_lib/data/dictionary.txt:eneable->enable
codespell_lib/data/dictionary.txt:escapeable->escapable
codespell_lib/data/dictionary.txt:executeable->executable
codespell_lib/data/dictionary.txt:forseeable->foreseeable
codespell_lib/data/dictionary.txt:indefineable->undefinable
codespell_lib/data/dictionary.txt:interopeable->interoperable
codespell_lib/data/dictionary.txt:joineable->joinable
codespell_lib/data/dictionary.txt:knoledgeable->knowledgeable
codespell_lib/data/dictionary.txt:knowladgeable->knowledgeable
codespell_lib/data/dictionary.txt:knowlageable->knowledgeable
codespell_lib/data/dictionary.txt:knowlegdeable->knowledgeable
codespell_lib/data/dictionary.txt:knowlegeable->knowledgeable
codespell_lib/data/dictionary.txt:knownledgeable->knowledgeable
codespell_lib/data/dictionary.txt:knwoledgeable->knowledgeable
codespell_lib/data/dictionary.txt:konwledgeable->knowledgeable
codespell_lib/data/dictionary.txt:kowledgeable->knowledgeable
codespell_lib/data/dictionary.txt:kwnoledgeable->knowledgeable
codespell_lib/data/dictionary.txt:kwoledgeable->knowledgeable
codespell_lib/data/dictionary.txt:measureable->measurable
codespell_lib/data/dictionary.txt:migrateable->migratable
codespell_lib/data/dictionary.txt:noteable->notable
codespell_lib/data/dictionary.txt:overrideable->overridable
codespell_lib/data/dictionary.txt:overwriteable->overwritable
codespell_lib/data/dictionary.txt:prefereable->preferable
codespell_lib/data/dictionary.txt:re-useable->reusable
codespell_lib/data/dictionary.txt:reacheable->reachable
codespell_lib/data/dictionary.txt:readeable->readable
codespell_lib/data/dictionary.txt:rearrangteable->rearrangeable
codespell_lib/data/dictionary.txt:recognizeable->recognizable
codespell_lib/data/dictionary.txt:redeable->readable
codespell_lib/data/dictionary.txt:redistributeable->redistributable
codespell_lib/data/dictionary.txt:reduceable->reducible
codespell_lib/data/dictionary.txt:relocateable->relocatable
codespell_lib/data/dictionary.txt:removeable->removable
codespell_lib/data/dictionary.txt:restoreable->restorable
codespell_lib/data/dictionary.txt:reuseable->reusable
codespell_lib/data/dictionary.txt:rotateable->rotatable
codespell_lib/data/dictionary.txt:scaleable->scalable
codespell_lib/data/dictionary.txt:searcheable->searchable
codespell_lib/data/dictionary.txt:solveable->solvable
codespell_lib/data/dictionary.txt:storeable->storable
codespell_lib/data/dictionary.txt:suiteable->suitable
codespell_lib/data/dictionary.txt:suposeable->supposable
codespell_lib/data/dictionary.txt:supposeable->supposable
codespell_lib/data/dictionary.txt:unbeliveable->unbelievable
codespell_lib/data/dictionary.txt:undecideable->undecidable
codespell_lib/data/dictionary.txt:undesireable->undesirable
codespell_lib/data/dictionary.txt:uneforceable->unenforceable
codespell_lib/data/dictionary.txt:unforgiveable->unforgivable
codespell_lib/data/dictionary.txt:ungeneralizeable->ungeneralizable
codespell_lib/data/dictionary.txt:unoticeable->unnoticeable
codespell_lib/data/dictionary.txt:unparseable->unparsable
codespell_lib/data/dictionary.txt:unreacheable->unreachable
codespell_lib/data/dictionary.txt:untranslateable->untranslatable
codespell_lib/data/dictionary.txt:unuseable->unusable
codespell_lib/data/dictionary.txt:uptadeable->updatable
codespell_lib/data/dictionary.txt:useable->usable
codespell_lib/data/dictionary.txt:valueable->valuable
codespell_lib/data/dictionary.txt:varieable->variable
codespell_lib/data/dictionary.txt:visibleable->visible
codespell_lib/data/dictionary.txt:vulneable->vulnerable
codespell_lib/data/dictionary.txt:vulnreable->vulnerable
codespell_lib/data/dictionary.txt:writeable->writable
$ 
```
</details>

**Comment by polluks** [comment]
Please take a look https://english.stackexchange.com/a/623194/273648

**Comment by DimitriPapadopoulos** [comment]
Do you suggest we keep the dictionary as is?

The above is a good summary of what I have been documenting previously. However, many native speakers don't like or do not blindly follow grammar rules: they insist on allowing alternative spellings, even when targeting a wider international public.

**Comment by polluks** [comment]
ok
