### ISSUE TITLE
Q: plans to have a conda package with conda-forge (A: Yes. We are looking for a maintainer. Any interest?)

### ISSUE THREAD

**Issue by thorade** [codespell-project/codespell#633]
Just a question:
Did you ever consider adding a recipe to conda-forge?
https://anaconda.org/conda-forge
https://conda-forge.org/
Some anaconda users prefer conda over pip.

**Comment by luzpaz** [comment]
@thdot would you be open to creating one ?

**Comment by thorade** [comment]
I started looking into when I filed this issue, but then gave up. It should be possible to somehow reuse the pip/pypi instructions, but I have never done that either.
I could look into it again, if you consider it an useful addition.

**Comment by dopplershift** [comment]
[Already done](https://github.com/conda-forge/codespell-feedstock). Happy to add anyone interested as a maintainer.

**Comment by luzpaz** [comment]
What's involved in being a maintainer?

**Comment by dopplershift** [comment]
Keeping the recipe in that GitHub repository up to date. That usually means periodically merging Pull Requests that come in from the various bots that automatically issue them for version updates, migrations for Python versions (or other "special" dependencies") or architecture updates. I mean, you *could* manually bump the recipe for new versions, but I usually let the bot handle making the updates--unless something goes wrong.

Since codespell is pure Python with no dependencies, I'd expect it to really only need updating to stay in-step with new releases from here. There are also more elaborate [maintainer docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-pkgs).

**Comment by larsoner** [comment]
This has been done by @dopplershift !
